sudo: required

services:
  - docker

language: go
go:
  - 1.7.3

env:
  global:
    - PATH=/home/travis/gopath/bin:$PATH
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=kbudde/rabbitmq-exporter
before_install:
  - go get github.com/mitchellh/gox

  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/aktau/github-release
  - git checkout -B ${TRAVIS_BRANCH}

install:
  - go get -t ./...

script:
  - go test -tags integration -v -covermode=count -coverprofile=coverage.out ./

after_success:
#Build Docker image
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - make docker DOCKER_IMAGE_NAME=$REPO DOCKER_IMAGE_TAG=$TAG
  - docker push $REPO
  
#Build dist releases 
  - make tarballs
  - promu release .tarballs
  
#Submit coverage
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
