sudo: required

services:
  - docker

language: go
go:
  - 1.9

env:
  global:
    - PATH=/home/travis/gopath/bin:$PATH
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=kbudde/rabbitmq-exporter
    - DEP_VERSION="0.3.2"
before_install:
  - go get github.com/mitchellh/gox

  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/aktau/github-release
  - git checkout -B ${TRAVIS_BRANCH}

  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure

script:
  - go test -tags integration -covermode=count -coverprofile=coverage.out ./

after_success:
#Build Docker image
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - make docker DOCKER_IMAGE_NAME=$REPO DOCKER_IMAGE_TAG=$TAG
  - docker push $REPO
  
#Build dist releases 
  - if [ -n "$TRAVIS_TAG" ]; then make tarballs && promu release .tarballs ; fi
  
#Submit coverage
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
